name: Build and Deploy Script

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Adding Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build
      - name: Deploy to gh pages
        run: |
          npm run ng -- deploy --repo="https://github.com/RomanenkoStud/geo-data.git" --base-href=/geo-data/ --name=RomanenkoStud --email=vlm.9v.romanenko.pavlo@gmail.com
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
